-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.admin_users (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  email character varying NOT NULL UNIQUE,
  username character varying UNIQUE,
  password_hash character varying NOT NULL,
  senha character varying,
  name character varying,
  nome character varying,
  role character varying DEFAULT 'admin'::character varying,
  cargo character varying,
  is_active boolean DEFAULT true,
  ativo boolean DEFAULT true,
  last_login timestamp with time zone,
  ultimo_acesso timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  preferences jsonb DEFAULT '{"darkMode": false, "language": "pt-BR", "pushNotifications": true, "emailNotifications": true}'::jsonb,
  avatar_url text,
  login_count integer DEFAULT 0,
  last_login_at timestamp with time zone,
  CONSTRAINT admin_users_pkey PRIMARY KEY (id)
);
CREATE TABLE public.api_keys (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL,
  key character varying NOT NULL UNIQUE,
  description text,
  status character varying DEFAULT 'active'::character varying CHECK (status::text = ANY (ARRAY['active'::character varying, 'inactive'::character varying]::text[])),
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  last_used timestamp with time zone,
  request_count integer DEFAULT 0,
  rate_limit integer DEFAULT 1000,
  allowed_origins jsonb DEFAULT '[]'::jsonb,
  permissions jsonb DEFAULT '["read"]'::jsonb,
  CONSTRAINT api_keys_pkey PRIMARY KEY (id)
);
CREATE TABLE public.api_metrics (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  api_key_id uuid,
  date_hour timestamp with time zone NOT NULL,
  request_count integer DEFAULT 0,
  error_count integer DEFAULT 0,
  avg_response_time integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT api_metrics_pkey PRIMARY KEY (id),
  CONSTRAINT api_metrics_api_key_id_fkey FOREIGN KEY (api_key_id) REFERENCES public.api_keys(id)
);
CREATE TABLE public.api_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  api_key_id uuid,
  method character varying NOT NULL,
  endpoint character varying NOT NULL,
  status_code integer NOT NULL,
  response_time integer DEFAULT 0,
  ip_address inet,
  user_agent text,
  request_body jsonb,
  response_body jsonb,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT api_requests_pkey PRIMARY KEY (id),
  CONSTRAINT api_requests_api_key_id_fkey FOREIGN KEY (api_key_id) REFERENCES public.api_keys(id)
);
CREATE TABLE public.app_settings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  section character varying NOT NULL,
  settings jsonb NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT app_settings_pkey PRIMARY KEY (id)
);
CREATE TABLE public.banks (
  id integer NOT NULL DEFAULT nextval('banks_id_seq'::regclass),
  code character varying NOT NULL UNIQUE,
  name character varying NOT NULL,
  icon_url text,
  color character varying,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT banks_pkey PRIMARY KEY (id)
);
CREATE TABLE public.bd_ativo (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  num bigint,
  CONSTRAINT bd_ativo_pkey PRIMARY KEY (id)
);
CREATE TABLE public.blog_posts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title character varying NOT NULL,
  slug character varying NOT NULL UNIQUE,
  excerpt text,
  content text NOT NULL,
  featured_image_url text,
  meta_title character varying,
  meta_description text,
  meta_keywords ARRAY,
  category character varying,
  tags ARRAY,
  author_id uuid,
  author_name character varying,
  status character varying DEFAULT 'draft'::character varying CHECK (status::text = ANY (ARRAY['draft'::character varying, 'published'::character varying, 'archived'::character varying]::text[])),
  is_featured boolean DEFAULT false,
  views_count integer DEFAULT 0,
  likes_count integer DEFAULT 0,
  published_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT blog_posts_pkey PRIMARY KEY (id),
  CONSTRAINT blog_posts_author_id_fkey FOREIGN KEY (author_id) REFERENCES public.admin_users(id)
);
CREATE TABLE public.categorias (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  nome character varying NOT NULL UNIQUE,
  icone character varying DEFAULT '📦'::character varying,
  ativo boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT categorias_pkey PRIMARY KEY (id)
);
CREATE TABLE public.contact_messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL,
  email character varying NOT NULL,
  phone character varying,
  company character varying,
  subject character varying,
  message text NOT NULL,
  status character varying DEFAULT 'new'::character varying CHECK (status::text = ANY (ARRAY['new'::character varying, 'read'::character varying, 'replied'::character varying, 'archived'::character varying]::text[])),
  priority character varying DEFAULT 'normal'::character varying CHECK (priority::text = ANY (ARRAY['low'::character varying, 'normal'::character varying, 'high'::character varying, 'urgent'::character varying]::text[])),
  replied_at timestamp with time zone,
  replied_by uuid,
  reply_message text,
  ip_address inet,
  user_agent text,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT contact_messages_pkey PRIMARY KEY (id),
  CONSTRAINT contact_messages_replied_by_fkey FOREIGN KEY (replied_by) REFERENCES public.admin_users(id)
);
CREATE TABLE public.daily_financial_summary (
  id integer NOT NULL DEFAULT nextval('daily_financial_summary_id_seq'::regclass),
  summary_date date NOT NULL UNIQUE,
  total_revenue numeric NOT NULL,
  total_employee_payments numeric NOT NULL,
  total_garcom_percentage numeric NOT NULL,
  num_active_employees integer NOT NULL DEFAULT 0,
  num_garcom_on_duty integer NOT NULL DEFAULT 0,
  calculation_details jsonb,
  synced_with_financial_data boolean DEFAULT false,
  financial_data_id integer,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT daily_financial_summary_pkey PRIMARY KEY (id),
  CONSTRAINT daily_financial_summary_financial_data_id_fkey FOREIGN KEY (financial_data_id) REFERENCES public.financial_data(id)
);
CREATE TABLE public.daily_payments (
  id integer NOT NULL DEFAULT nextval('daily_payments_id_seq'::regclass),
  employee_id integer NOT NULL,
  payment_date date NOT NULL,
  daily_revenue numeric NOT NULL DEFAULT 0.00,
  base_salary numeric NOT NULL,
  bonus numeric DEFAULT 0.00,
  deductions numeric DEFAULT 0.00,
  final_amount numeric NOT NULL,
  calculation_details jsonb,
  payment_status character varying NOT NULL DEFAULT 'pendente'::character varying CHECK (payment_status::text = ANY (ARRAY['pendente'::character varying, 'processando'::character varying, 'pago'::character varying, 'cancelado'::character varying]::text[])),
  payment_method character varying CHECK (payment_method::text = ANY (ARRAY['pix'::character varying, 'transferencia'::character varying, 'dinheiro'::character varying, 'cheque'::character varying]::text[])),
  paid_at timestamp with time zone,
  notes text,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT daily_payments_pkey PRIMARY KEY (id),
  CONSTRAINT daily_payments_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id)
);
CREATE TABLE public.employee_attendance (
  id integer NOT NULL DEFAULT nextval('employee_attendance_id_seq'::regclass),
  employee_id integer NOT NULL,
  attendance_date date NOT NULL,
  check_in time without time zone,
  check_out time without time zone,
  hours_worked numeric,
  status character varying NOT NULL DEFAULT 'presente'::character varying CHECK (status::text = ANY (ARRAY['presente'::character varying, 'ausente'::character varying, 'falta'::character varying, 'ferias'::character varying, 'folga'::character varying, 'atestado'::character varying]::text[])),
  notes text,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT employee_attendance_pkey PRIMARY KEY (id),
  CONSTRAINT employee_attendance_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id)
);
CREATE TABLE public.employee_bank_accounts (
  id integer NOT NULL DEFAULT nextval('employee_bank_accounts_id_seq'::regclass),
  employee_id integer NOT NULL,
  bank_id integer NOT NULL,
  account_type character varying NOT NULL CHECK (account_type::text = ANY (ARRAY['corrente'::character varying, 'poupanca'::character varying, 'salario'::character varying]::text[])),
  agency character varying NOT NULL,
  account_number character varying NOT NULL,
  account_digit character varying,
  pix_key_type character varying CHECK (pix_key_type::text = ANY (ARRAY['cpf'::character varying, 'email'::character varying, 'telefone'::character varying, 'chave_aleatoria'::character varying, 'qrcode'::character varying]::text[])),
  pix_key character varying,
  qr_code_pix text,
  is_primary boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT employee_bank_accounts_pkey PRIMARY KEY (id),
  CONSTRAINT employee_bank_accounts_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id),
  CONSTRAINT employee_bank_accounts_bank_id_fkey FOREIGN KEY (bank_id) REFERENCES public.banks(id)
);
CREATE TABLE public.employee_performance_metrics (
  id integer NOT NULL DEFAULT nextval('employee_performance_metrics_id_seq'::regclass),
  employee_id integer NOT NULL,
  metric_date date NOT NULL,
  total_earnings numeric DEFAULT 0.00,
  days_worked integer DEFAULT 0,
  average_daily_earnings numeric DEFAULT 0.00,
  total_bonus numeric DEFAULT 0.00,
  total_deductions numeric DEFAULT 0.00,
  performance_score numeric,
  metrics_details jsonb,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT employee_performance_metrics_pkey PRIMARY KEY (id),
  CONSTRAINT employee_performance_metrics_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id)
);
CREATE TABLE public.employees (
  id integer NOT NULL DEFAULT nextval('employees_id_seq'::regclass),
  name character varying NOT NULL,
  email character varying NOT NULL UNIQUE,
  phone character varying,
  photo_url text,
  position character varying NOT NULL CHECK ("position"::text = ANY (ARRAY['garcom'::character varying, 'balconista'::character varying, 'barmen'::character varying, 'cozinheiro'::character varying, 'cozinheiro_chef'::character varying]::text[])),
  hire_date date NOT NULL DEFAULT CURRENT_DATE,
  status character varying NOT NULL DEFAULT 'ativo'::character varying CHECK (status::text = ANY (ARRAY['ativo'::character varying, 'inativo'::character varying, 'ferias'::character varying, 'afastado'::character varying]::text[])),
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT employees_pkey PRIMARY KEY (id)
);
CREATE TABLE public.faq_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  question text NOT NULL,
  answer text NOT NULL,
  category character varying NOT NULL,
  display_order integer DEFAULT 0,
  is_active boolean DEFAULT true,
  views_count integer DEFAULT 0,
  helpful_count integer DEFAULT 0,
  not_helpful_count integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT faq_items_pkey PRIMARY KEY (id)
);
CREATE TABLE public.financial_data (
  id bigint NOT NULL DEFAULT nextval('financial_data_id_seq'::regclass),
  full_day character varying NOT NULL,
  amount numeric NOT NULL,
  total numeric NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT financial_data_pkey PRIMARY KEY (id)
);
CREATE TABLE public.leads (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL,
  email character varying NOT NULL,
  phone character varying,
  company character varying,
  source character varying,
  utm_source character varying,
  utm_medium character varying,
  utm_campaign character varying,
  message text,
  interested_in character varying,
  status character varying DEFAULT 'new'::character varying CHECK (status::text = ANY (ARRAY['new'::character varying, 'contacted'::character varying, 'qualified'::character varying, 'converted'::character varying, 'lost'::character varying]::text[])),
  contacted_at timestamp with time zone,
  converted_to_tenant_id uuid,
  metadata jsonb DEFAULT '{}'::jsonb,
  ip_address inet,
  user_agent text,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT leads_pkey PRIMARY KEY (id),
  CONSTRAINT leads_converted_to_tenant_id_fkey FOREIGN KEY (converted_to_tenant_id) REFERENCES public.tenants(id)
);
CREATE TABLE public.logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  action character varying NOT NULL,
  entity_type character varying,
  entity_id uuid,
  description text,
  ip_address inet,
  user_agent text,
  metadata jsonb,
  created_at timestamp with time zone DEFAULT now(),
  username text NOT NULL DEFAULT 'system'::text,
  resource text NOT NULL DEFAULT 'system'::text,
  resource_id text,
  details jsonb DEFAULT '{}'::jsonb,
  severity text NOT NULL DEFAULT 'info'::text,
  category text NOT NULL DEFAULT 'system'::text,
  session_id text,
  execution_time integer,
  status text DEFAULT 'success'::text,
  error_message text,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT logs_pkey PRIMARY KEY (id),
  CONSTRAINT logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.admin_users(id)
);
CREATE TABLE public.menu_diario (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  planejamento_semanal_id uuid NOT NULL,
  menu_item_id uuid NOT NULL,
  data_planejada date NOT NULL,
  periodo_refeicao character varying NOT NULL DEFAULT 'almoco'::character varying CHECK (periodo_refeicao::text = ANY (ARRAY['cafe_manha'::character varying::text, 'almoco'::character varying::text, 'jantar'::character varying::text])),
  quantidade_estimada integer NOT NULL DEFAULT 1,
  receita_estimada numeric DEFAULT 0,
  status character varying DEFAULT 'planejado'::character varying CHECK (status::text = ANY (ARRAY['planejado'::character varying::text, 'preparando'::character varying::text, 'pronto'::character varying::text, 'cancelado'::character varying::text])),
  observacoes text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT menu_diario_pkey PRIMARY KEY (id),
  CONSTRAINT menu_diario_planejamento_semanal_id_fkey FOREIGN KEY (planejamento_semanal_id) REFERENCES public.planejamento_semanal(id),
  CONSTRAINT menu_diario_menu_item_id_fkey FOREIGN KEY (menu_item_id) REFERENCES public.menu_items(id)
);
CREATE TABLE public.menu_item_ingredientes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  menu_item_id uuid NOT NULL,
  produto_id uuid NOT NULL,
  quantidade numeric NOT NULL CHECK (quantidade > 0::numeric),
  unidade character varying NOT NULL DEFAULT 'unidade'::character varying,
  opcional boolean DEFAULT false,
  observacoes text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT menu_item_ingredientes_pkey PRIMARY KEY (id),
  CONSTRAINT menu_item_ingredientes_menu_item_id_fkey FOREIGN KEY (menu_item_id) REFERENCES public.menu_items(id),
  CONSTRAINT menu_item_ingredientes_produto_id_fkey FOREIGN KEY (produto_id) REFERENCES public.produtos(id)
);
CREATE TABLE public.menu_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  nome character varying NOT NULL,
  descricao text,
  categoria_id uuid,
  preco_venda numeric NOT NULL,
  custo_ingredientes numeric NOT NULL DEFAULT 0,
  tempo_preparo integer NOT NULL DEFAULT 0,
  dificuldade character varying DEFAULT 'medium'::character varying CHECK (dificuldade::text = ANY (ARRAY['easy'::character varying::text, 'medium'::character varying::text, 'hard'::character varying::text])),
  porcoes integer DEFAULT 1,
  score_popularidade integer DEFAULT 0 CHECK (score_popularidade >= 0 AND score_popularidade <= 100),
  disponivel boolean DEFAULT true,
  destaque boolean DEFAULT false,
  calorias integer,
  proteina_g numeric,
  carboidratos_g numeric,
  gordura_g numeric,
  tags ARRAY,
  criado_por uuid,
  ativo boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT menu_items_pkey PRIMARY KEY (id),
  CONSTRAINT menu_items_categoria_id_fkey FOREIGN KEY (categoria_id) REFERENCES public.categorias(id),
  CONSTRAINT menu_items_criado_por_fkey FOREIGN KEY (criado_por) REFERENCES public.admin_users(id)
);
CREATE TABLE public.movements (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  product_id uuid NOT NULL,
  type character varying NOT NULL,
  quantity integer NOT NULL,
  previous_stock integer,
  new_stock integer,
  unit_cost numeric,
  total_cost numeric,
  notes text,
  supplier character varying,
  invoice_number character varying,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT movements_pkey PRIMARY KEY (id),
  CONSTRAINT movements_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.produtos(id),
  CONSTRAINT movements_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.admin_users(id)
);
CREATE TABLE public.payment_audit_log (
  id integer NOT NULL DEFAULT nextval('payment_audit_log_id_seq'::regclass),
  payment_id integer,
  employee_id integer NOT NULL,
  action character varying NOT NULL,
  old_values jsonb,
  new_values jsonb,
  changed_by uuid,
  ip_address inet,
  user_agent text,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT payment_audit_log_pkey PRIMARY KEY (id),
  CONSTRAINT payment_audit_log_payment_id_fkey FOREIGN KEY (payment_id) REFERENCES public.daily_payments(id),
  CONSTRAINT payment_audit_log_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id),
  CONSTRAINT payment_audit_log_changed_by_fkey FOREIGN KEY (changed_by) REFERENCES public.admin_users(id)
);
CREATE TABLE public.permissions (
  id character varying NOT NULL,
  name character varying NOT NULL,
  description text,
  category character varying NOT NULL DEFAULT 'sistema'::character varying,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT permissions_pkey PRIMARY KEY (id)
);
CREATE TABLE public.planejamento_semanal (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  data_inicio date NOT NULL,
  data_fim date NOT NULL,
  status character varying DEFAULT 'ativo'::character varying CHECK (status::text = ANY (ARRAY['rascunho'::character varying::text, 'planejado'::character varying::text, 'ativo'::character varying::text, 'concluido'::character varying::text])),
  observacoes text,
  receita_estimada numeric DEFAULT 0,
  criado_por uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT planejamento_semanal_pkey PRIMARY KEY (id),
  CONSTRAINT planejamento_semanal_criado_por_fkey FOREIGN KEY (criado_por) REFERENCES public.admin_users(id)
);
CREATE TABLE public.produtos (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  nome character varying NOT NULL,
  categoria_id uuid,
  preco numeric NOT NULL DEFAULT 0,
  custo numeric DEFAULT 0,
  current_stock integer DEFAULT 0,
  estoque_atual integer DEFAULT 0,
  min_stock integer DEFAULT 0,
  estoque_minimo integer DEFAULT 0,
  max_stock integer,
  unidade character varying DEFAULT 'unidade'::character varying,
  descricao text,
  codigo_barras character varying,
  ativo boolean DEFAULT true,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT produtos_pkey PRIMARY KEY (id),
  CONSTRAINT produtos_categoria_id_fkey FOREIGN KEY (categoria_id) REFERENCES public.categorias(id),
  CONSTRAINT produtos_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.admin_users(id)
);
CREATE TABLE public.reports (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title character varying NOT NULL,
  type character varying,
  filters jsonb,
  data jsonb,
  generated_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT reports_pkey PRIMARY KEY (id),
  CONSTRAINT reports_generated_by_fkey FOREIGN KEY (generated_by) REFERENCES public.admin_users(id)
);
CREATE TABLE public.role_permissions (
  role_id character varying NOT NULL,
  permission_id character varying NOT NULL,
  granted boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT role_permissions_pkey PRIMARY KEY (role_id, permission_id),
  CONSTRAINT role_permissions_role_id_fkey FOREIGN KEY (role_id) REFERENCES public.user_roles(id),
  CONSTRAINT role_permissions_permission_id_fkey FOREIGN KEY (permission_id) REFERENCES public.permissions(id)
);
CREATE TABLE public.salary_configs (
  id integer NOT NULL DEFAULT nextval('salary_configs_id_seq'::regclass),
  position character varying NOT NULL UNIQUE CHECK ("position"::text = ANY (ARRAY['garcom'::character varying, 'balconista'::character varying, 'barmen'::character varying, 'cozinheiro'::character varying, 'cozinheiro_chef'::character varying]::text[])),
  calculation_type character varying NOT NULL CHECK (calculation_type::text = ANY (ARRAY['percentage'::character varying, 'fixed'::character varying, 'mixed'::character varying]::text[])),
  fixed_daily_amount numeric DEFAULT 0.00,
  percentage_rate numeric DEFAULT 0.00,
  min_daily_guarantee numeric DEFAULT 0.00,
  max_daily_limit numeric,
  description text,
  active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT salary_configs_pkey PRIMARY KEY (id)
);
CREATE TABLE public.subscription_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  plan_id uuid NOT NULL,
  billing_cycle character varying NOT NULL CHECK (billing_cycle::text = ANY (ARRAY['monthly'::character varying, 'yearly'::character varying]::text[])),
  amount numeric NOT NULL,
  currency character varying DEFAULT 'BRL'::character varying,
  starts_at timestamp with time zone NOT NULL,
  ends_at timestamp with time zone,
  status character varying NOT NULL DEFAULT 'active'::character varying CHECK (status::text = ANY (ARRAY['active'::character varying, 'cancelled'::character varying, 'expired'::character varying]::text[])),
  cancelled_at timestamp with time zone,
  cancellation_reason text,
  payment_method character varying,
  payment_status character varying DEFAULT 'pending'::character varying CHECK (payment_status::text = ANY (ARRAY['pending'::character varying, 'paid'::character varying, 'failed'::character varying, 'refunded'::character varying]::text[])),
  paid_at timestamp with time zone,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT subscription_history_pkey PRIMARY KEY (id),
  CONSTRAINT subscription_history_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT subscription_history_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES public.subscription_plans(id)
);
CREATE TABLE public.subscription_plans (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL,
  slug character varying NOT NULL UNIQUE,
  description text,
  price_monthly numeric NOT NULL DEFAULT 0.00,
  price_yearly numeric NOT NULL DEFAULT 0.00,
  currency character varying DEFAULT 'BRL'::character varying,
  max_users integer NOT NULL DEFAULT 5,
  max_storage_mb integer NOT NULL DEFAULT 1000,
  max_products integer DEFAULT '-1'::integer,
  max_transactions_month integer DEFAULT '-1'::integer,
  features jsonb DEFAULT '{}'::jsonb,
  is_active boolean DEFAULT true,
  is_popular boolean DEFAULT false,
  is_recommended boolean DEFAULT false,
  display_order integer DEFAULT 0,
  trial_days integer DEFAULT 14,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT subscription_plans_pkey PRIMARY KEY (id)
);
CREATE TABLE public.suppliers (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name character varying NOT NULL,
  contact character varying,
  phone character varying,
  email character varying,
  address text,
  category character varying,
  status character varying DEFAULT 'active'::character varying CHECK (status::text = ANY (ARRAY['active'::character varying, 'inactive'::character varying]::text[])),
  last_order timestamp with time zone,
  products_count integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  CONSTRAINT suppliers_pkey PRIMARY KEY (id)
);
CREATE TABLE public.support_conversations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  subject text NOT NULL,
  status text NOT NULL DEFAULT 'open'::text CHECK (status = ANY (ARRAY['open'::text, 'closed'::text])),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT support_conversations_pkey PRIMARY KEY (id)
);
CREATE TABLE public.support_messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  conversation_id uuid NOT NULL,
  sender_id uuid NOT NULL,
  sender_role text NOT NULL CHECK (sender_role = ANY (ARRAY['admin'::text, 'support'::text])),
  content text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT support_messages_pkey PRIMARY KEY (id),
  CONSTRAINT support_messages_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES public.support_conversations(id)
);
CREATE TABLE public.support_participants (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  conversation_id uuid NOT NULL,
  user_id uuid NOT NULL,
  role text NOT NULL CHECK (role = ANY (ARRAY['admin'::text, 'support'::text])),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT support_participants_pkey PRIMARY KEY (id),
  CONSTRAINT support_participants_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES public.support_conversations(id)
);
CREATE TABLE public.system_alerts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  type character varying NOT NULL CHECK (type::text = ANY (ARRAY['critical'::character varying, 'warning'::character varying, 'info'::character varying, 'success'::character varying]::text[])),
  category character varying NOT NULL,
  title character varying NOT NULL,
  description text NOT NULL,
  details text,
  icon character varying NOT NULL,
  resolved boolean NOT NULL DEFAULT false,
  resolved_at timestamp with time zone,
  auto_generated boolean NOT NULL DEFAULT true,
  priority integer NOT NULL DEFAULT 1,
  affected_entity character varying,
  entity_id character varying,
  action_required boolean DEFAULT false,
  suggested_actions jsonb,
  metadata jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT system_alerts_pkey PRIMARY KEY (id)
);
CREATE TABLE public.tenant_invitations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  email character varying NOT NULL CHECK (email::text = lower(email::text)),
  role character varying DEFAULT 'user'::character varying,
  invited_by uuid,
  status character varying DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'accepted'::character varying, 'rejected'::character varying, 'expired'::character varying]::text[])),
  token character varying NOT NULL UNIQUE,
  expires_at timestamp with time zone NOT NULL,
  accepted_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT tenant_invitations_pkey PRIMARY KEY (id),
  CONSTRAINT tenant_invitations_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT tenant_invitations_invited_by_fkey FOREIGN KEY (invited_by) REFERENCES public.admin_users(id)
);
CREATE TABLE public.tenant_users (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  admin_user_id uuid,
  email character varying NOT NULL CHECK (email::text = lower(email::text)),
  name character varying NOT NULL,
  role character varying DEFAULT 'user'::character varying,
  is_active boolean DEFAULT true,
  is_owner boolean DEFAULT false,
  permissions jsonb DEFAULT '[]'::jsonb,
  invited_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  joined_at timestamp with time zone,
  last_login_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT tenant_users_pkey PRIMARY KEY (id),
  CONSTRAINT tenant_users_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT tenant_users_admin_user_id_fkey FOREIGN KEY (admin_user_id) REFERENCES public.admin_users(id)
);
CREATE TABLE public.tenants (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL CHECK (length(TRIM(BOTH FROM name)) > 0),
  slug character varying NOT NULL UNIQUE CHECK (slug::text = lower(slug::text)),
  email character varying NOT NULL,
  phone character varying,
  cnpj character varying,
  address_street text,
  address_number character varying,
  address_complement character varying,
  address_neighborhood character varying,
  address_city character varying,
  address_state character varying,
  address_zip_code character varying,
  address_country character varying DEFAULT 'Brasil'::character varying,
  status character varying DEFAULT 'trial'::character varying CHECK (status::text = ANY (ARRAY['trial'::character varying, 'active'::character varying, 'suspended'::character varying, 'cancelled'::character varying]::text[])),
  subscription_plan_id uuid,
  subscription_status character varying DEFAULT 'trialing'::character varying CHECK (subscription_status::text = ANY (ARRAY['trialing'::character varying, 'active'::character varying, 'past_due'::character varying, 'cancelled'::character varying]::text[])),
  trial_ends_at timestamp with time zone,
  subscription_started_at timestamp with time zone,
  subscription_ends_at timestamp with time zone,
  settings jsonb DEFAULT '{}'::jsonb,
  logo_url text,
  primary_color character varying DEFAULT '#3b82f6'::character varying,
  max_users integer DEFAULT 5,
  current_users integer DEFAULT 0,
  max_storage_mb integer DEFAULT 1000,
  current_storage_mb numeric DEFAULT 0,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  created_by uuid,
  CONSTRAINT tenants_pkey PRIMARY KEY (id)
);
CREATE TABLE public.testimonials (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  author_name character varying NOT NULL,
  author_role character varying,
  author_company character varying,
  author_avatar_url text,
  content text NOT NULL,
  rating integer CHECK (rating >= 1 AND rating <= 5),
  is_featured boolean DEFAULT false,
  is_approved boolean DEFAULT false,
  display_order integer DEFAULT 0,
  tenant_id uuid,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT testimonials_pkey PRIMARY KEY (id),
  CONSTRAINT testimonials_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id)
);
CREATE TABLE public.user_roles (
  id character varying NOT NULL,
  name character varying NOT NULL,
  description text,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT user_roles_pkey PRIMARY KEY (id)
);